<main class="donation-detail">
    <div class="donation-detail-shell">
        <a href="/tr/bagis" class="flow-back">← Tüm bağışlara dön</a>
        <div class="donation-detail-layout">
            <section class="donation-story" aria-label="Bağış hakkında">
                @if($card['image'])
                    <img class="donation-story-image" src="{{ $card['image'] }}" alt="{{ $card['title'] }}" width="800" height="640">
                @else
                    <div class="donation-story-placeholder">İyilik birlikte büyür.</div>
                @endif
                <div class="donation-story-copy"><p class="story-eyebrow">PAYLAŞTIKÇA ÇOĞALAN İYİLİK</p><h1>{{ $card['title'] }}</h1>
                    @if($description)<div class="story-description">{!! $description !!}</div>@else<p>{{ $card['description'] }}</p>@endif
                </div>
            </section>
            <section class="donation-form-column" aria-label="Bağış adımları">
                <header class="flow-intro"><h2>İyiliğe bir adım daha.</h2><span>Seçimlerinizi yapın, bağışınızı birlikte tamamlayalım.</span></header>
                {!! $flow !!}
            </section>
        </div>
    </div>
</main>
{!! $script !!}
<style>
.donation-detail{background:#fcfcfb;color:var(--color-primary,#024372);padding:24px 0 65px}.donation-detail-shell{max-width:1280px;margin:auto;padding:0 40px}.flow-back{display:inline-block;color:#7a8892;font-size:12px;margin-bottom:24px}.flow-back:hover{color:var(--color-primary)}.donation-detail-layout{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:48px;align-items:start}.flow-intro{margin-bottom:28px}.flow-intro>p,.story-eyebrow{font-size:10px;letter-spacing:.18em;color:#a48658;margin-bottom:8px}.flow-intro h1{font-size:34px;line-height:1.12;font-weight:500;letter-spacing:-.03em;margin-bottom:9px}.flow-intro>span{font-size:13px;color:#849099}.donation-story{position:sticky;top:118px}.donation-story-image{display:block;width:100%;height:auto;aspect-ratio:1.22;object-fit:cover;border-radius:18px}.donation-story-placeholder{aspect-ratio:1.22;display:grid;place-items:center;border-radius:18px;background:linear-gradient(135deg,#e9eff1,#f2ecdf);font-size:25px}.donation-story-copy{padding:25px 3px}.donation-story-copy h2{font-size:25px;font-weight:500;margin-bottom:12px;letter-spacing:-.02em}.donation-story-copy>p:last-child,.story-description{font-size:15px;line-height:1.8;color:#71808a}.story-description p+p{margin-top:14px}
.flow-step{position:relative;padding:0 0 25px 44px}.flow-step:before{content:"";position:absolute;left:15px;top:31px;bottom:0;width:1px;background:#e3e7e9;transition:background .3s}.flow-step:last-of-type:before{display:none}.flow-step.is-complete:before{background:#b8c9d5}.flow-step-heading{display:flex;align-items:center;min-height:32px;margin-bottom:12px}.flow-step-heading h2{font-size:17px;font-weight:500;color:#849099;transition:color .3s}.flow-step-number{position:absolute;left:0;top:0;display:grid;place-items:center;width:31px;height:31px;background:#f0f2f3;border:1px solid #e0e5e8;border-radius:50%;font-size:12px;font-weight:500;color:#9aa5ac;transition:background .3s,color .3s,border-color .3s}.flow-step.is-complete .flow-step-number{background:var(--color-primary);border-color:var(--color-primary);color:#fff}.flow-step.is-complete .flow-step-heading h2{color:var(--color-primary)}.flow-step-body>.grid{grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:9px!important}.flow-step-body>.grid>button{padding:12px!important;border-radius:10px!important;box-shadow:none!important;text-align:left;align-items:flex-start;gap:5px!important;min-height:45px}.flow-step-body>.grid>button>div,.flow-step-body>.grid>button>img{display:none}.flow-step-body>.grid>button span{font-size:12px}.flow-step-body>.grid>button.ring-2{background:#edf3f6!important;border-color:var(--color-primary)!important}.flow-step-body>.grid>button:hover{background:#f4f7f8}.flow-step-body>.grid>button:focus-visible{outline:2px solid var(--color-primary);outline-offset:2px}.flow-step-body .rounded-2xl{border-radius:12px!important;box-shadow:none!important}.flow-step-body .p-6{padding:16px!important}.flow-step-body .md\:grid-cols-3{grid-template-columns:1fr!important}.flow-step-body .md\:grid-cols-2{grid-template-columns:repeat(2,minmax(0,1fr))!important}.flow-field-label{display:block;font-size:12px;color:#71808a;margin-bottom:7px}.flow-field-label span{color:#9aa4aa}.flow-intention-input{width:100%;border:1px solid #dfe5e9;border-radius:9px;padding:11px 12px;font-size:13px;background:#fff;color:var(--color-primary)}.flow-field-hint{font-size:11px;color:#9aa4aa;margin-top:5px}.flow-end{margin-left:44px;margin-bottom:18px}.flow-end>div{border-radius:12px!important}.flow-end .grid{grid-template-columns:repeat(2,minmax(0,1fr))!important}.donation-detail .btn-donate{background:var(--color-primary);color:white;border-radius:10px;min-height:46px;font-size:14px}.flow-simple-heading{display:flex;align-items:center;gap:12px;font-size:19px}.flow-simple-heading>span{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;background:var(--color-primary);color:white;font-size:13px}.flow-simple form{padding:20px 0 0 43px!important}.flow-simple .btn-donate{width:100%}.donation-detail #bagis-formu{scroll-margin-top:130px}
@media(max-width:1000px){.donation-detail-layout{gap:28px}.donation-detail-shell{padding:0 24px}.flow-intro h1{font-size:28px}}
@media(max-width:700px){.donation-detail{padding:18px 0 90px}.donation-detail-shell{padding:0 18px}.donation-detail-layout{grid-template-columns:1fr;gap:30px}.donation-story{position:static}.flow-back{margin-bottom:19px}.flow-intro{margin-bottom:24px}.flow-step{padding-left:40px}.flow-end{margin-left:40px}.donation-story-image{aspect-ratio:1.35}.flow-simple form{padding-left:0!important}}
.donation-detail-layout{display:block}.donation-story{position:static;display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:44px;align-items:center}.donation-story-image,.donation-story-placeholder{aspect-ratio:1.8;max-height:340px}.donation-story-copy{padding:10px 0}.donation-story-copy h1{font-size:36px;line-height:1.12;font-weight:500;letter-spacing:-.035em;margin-bottom:14px}.donation-form-column{max-width:760px;margin:36px auto 0;padding-top:25px;border-top:1px solid #e4e9ec}.flow-intro{text-align:center;margin-bottom:27px}.flow-intro h2{font-size:25px;font-weight:500;letter-spacing:-.025em;margin-bottom:7px}
@media(max-width:700px){.donation-detail{padding-top:12px}.flow-back{margin-bottom:12px}.donation-story{grid-template-columns:1fr;gap:12px}.donation-story-image,.donation-story-placeholder{aspect-ratio:1.9;max-height:230px;border-radius:12px}.donation-story-copy{padding:0}.story-eyebrow{font-size:9px;margin-bottom:5px}.donation-story-copy h1{font-size:27px;margin-bottom:7px}.donation-story-copy>p:last-child,.story-description{font-size:13px;line-height:1.5}.story-description p+p{margin-top:8px}.donation-form-column{margin-top:19px;padding-top:18px}.flow-intro{margin-bottom:20px}.flow-intro h2{font-size:22px}.flow-intro>span{font-size:12px}}
@media(prefers-reduced-motion:reduce){.donation-detail *{transition:none!important}}
</style>
